### ISSUE TITLE
how to use  multi-scale test?

### ISSUE THREAD

**Issue by larsoncs** [VDIGPKU/CBNetV2#10]
Thank you again!,
I use img_scale=[(1600, 1400),(800, 700),(1200, 1050),(2000, 1750),(2400, 2100),(2800, 2450)] , but mAP less than img_scale=(1600, 1400).  can you tell me the reason?
@tingtingliangvs

**Comment by chuxiaojie** [comment]
We use `img_scale=[(1600, 1000), (1600, 1400), (1800, 1200), (1800, 1600)]` with `flip=True`
