### ISSUE TITLE
 where is the config of  "20e + 1x (swa)"?  (HTC (1600x1400 test))

### ISSUE THREAD

**Issue by larsoncs** [VDIGPKU/CBNetV2#3]
thks

**Comment by tingtingliangvs** [comment]
Hi, the test config is the same as 20e-HTC (1600x1400 test)

**Comment by larsoncs** [comment]
What's the difference of mAP 57.9 and 58.2 ? ,is the model?  ths

**Comment by larsoncs** [comment]
@tingtingliangvs

**Comment by tingtingliangvs** [comment]
mAP 57.9  is the accuracy of HTC Dual-Swin-B trained with 20 epochs, mAP 58.2 is the accuracy of the same model trained with another 12 epochs with [SWA](https://github.com/hyz-xmaster/swa_object_detection).
