### ISSUE TITLE
CascadeRCNN: init_weights() got an unexpected keyword argument 'pretrained'

### ISSUE THREAD

**Issue by hosea7456** [VDIGPKU/CBNetV2#5]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I was trying to run "cascade_mask_rcnn_cbv2_swin_small_patch4_window7_mstrain_400-1400_adamw_3x_coco.py" using the pretrained model "cascade_mask_rcnn_cbv2_swin_small_patch4_window7_mstrain_400-1400_adamw_3x_coco.pth" as:

    pretrained='./pretrain/cascade_mask_rcnn_cbv2_swin_small_patch4_window7_mstrain_400-1400_adamw_3x_coco.pth',
    backbone=dict(
        type='CBSwinTransformer',
    ),

But a bug has appearing:
****************************************************************************************************************************************
2021-07-09 06:58:51,846 - mmdet - INFO - load model from: ./pretrain/cascade_mask_rcnn_cbv2_swin_small_patch4_window7_mstrain_400-1400_adamw_3x_coco.pth
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "CBNetV2/mmdet/models/detectors/cascade_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "CBNetV2/mmdet/models/detectors/two_stage.py", line 48, in __init__
    self.init_weights(pretrained=pretrained)
  File "CBNetV2/mmdet/models/detectors/two_stage.py", line 68, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
TypeError: init_weights() got an unexpected keyword argument 'pretrained'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 164, in main
    test_cfg=cfg.get('test_cfg'))
  File "CBNetV2/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "CBNetV2/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CascadeRCNN: init_weights() got an unexpected keyword argument 'pretrained'
****************************************************************************************************************************************
How can I solve this problem? Thank you!

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hosea7456** [comment]
I am sorry. The error above was caused by the mismatch version of mmdet. I solved it after I updated the mmdet.

**Comment by hosea7456** [comment]
I am sorry. The error above was caused by the mismatch version of mmdet. I solved it after I updated the mmdet.
But a new error has created:
****************************************************************************************************************************************
/CBNetV2/mmdet/models/detectors/two_stage.py:28: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/CBNetV2/mmdet/core/anchor/builder.py:16: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 162, in main
    model.init_weights()
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/CBNetV2/mmdet/models/backbones/cbnet.py", line 333, in init_weights
    m.init_weights()
  File "/CBNetV2/mmdet/models/backbones/swin_transformer.py", line 697, in init_weights
    load_checkpoint(self, self.pretrained, strict=False, logger=logger)
  File "/CBNetV2/mmcv_custom/checkpoint.py", line 340, in load_checkpoint
    table_current = model.state_dict()[table_key]
KeyError: 'backbone.cb_modules.0.layers.0.blocks.0.attn.relative_position_bias_table'
****************************************************************************************************************************************

What should I do then it can be solved?

**Comment by chuxiaojie** [comment]
You may try using `load_from` instead of `pretrained`. 
More information can be found at [https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/finetune.md](url).

**Comment by hosea7456** [comment]
@chuxiaojie 
Thanks a lot. I was stuck in the old version. I can runing the code sucessful now. Thank you again
