### ISSUE TITLE
ERROR 404 NOT FOUND - get_started.md

### ISSUE THREAD

**Issue by Quentinmht** [VDIGPKU/CBNetV2#53]
Hello,

Thanks a lot for your work and this model. Just a quick message to tell you that the get_started.md file is no longer accessible. We have a 404 Not found.

Quentin

**Comment by tingtingliangvs** [comment]
Hi, thanks for reporting. It's fixed. Pleased refer to [mmdet official repository](https://github.com/open-mmlab/mmdetection) for more details.
