### ISSUE TITLE
Could you please make sure running successfully before open source?

### ISSUE THREAD

**Issue by mitming** [VDIGPKU/CBNetV2#55]
Hi, @tingtingliangvs 

I tried to run the code directly without any modification, however, there are still a log of bugs, especially for `htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py`

Could you please check the code again and fix these bugs?

**Comment by tingtingliangvs** [comment]
Would you please report the bug log?

**Comment by mitming** [comment]
> Would you please report the bug log?

I am sorry for the rudeness. I tried to modify the code and it finally works. Thanks for your contribution.
