### ISSUE TITLE
Can you release the DB-Swin-L of config and model？

### ISSUE THREAD

**Issue by larsoncs** [VDIGPKU/CBNetV2#9]
thank you for your share!

**Comment by tingtingliangvs** [comment]
The config and model will be released when the paper is submitted.

**Comment by larsoncs** [comment]
thks，about what time?

**Comment by WangBoying** [comment]
@larsoncs haha, You can predict a receiving time for the author.

**Comment by tingtingliangvs** [comment]
Probably in one or two weeks.
